bump_version: null
lint: {}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Alex Epstein
  description: Makes gene count matrix from single-cell combinatorial indexing data
  force: false
  is_nfcore: true
  name: sciflow
  org: nf-core
  outdir: .
  skip_features: []
  version: 1.0.0dev
update: null
